create type stage_type as enum ('QUALIFYING', 'PLAY_OFF');

alter type stage_type owner to postgres;

create type stage_status as enum ('WAITING', 'ACTIVE', 'GRADING', 'FINISHED');

alter type stage_status owner to postgres;

create table if not exists competition
(
    id            bigint generated always as identity
        constraint competition_pk
            primary key,
    uuid          uuid                     not null,
    title         varchar(255)             not null,
    avatar_link   text                     not null,
    rules_link    text                     not null,
    date_of_start timestamp with time zone not null
);

alter table competition
    owner to postgres;

create table if not exists stage
(
    id             bigint generated always as identity
        constraint stage_pk
            primary key,
    uuid           uuid                                                                       not null,
    title          varchar(255)                                                               not null,
    status         my_singer.stage_status   default 'WAITING'::my_singer.stage_status         not null,
    type           my_singer.stage_type     default 'QUALIFYING'::my_singer.stage_type        not null,
    competition_id bigint                                                                     not null
        constraint stage_competition_fk
            references competition,
    date_start     timestamp with time zone default CURRENT_TIMESTAMP                         not null,
    date_end       timestamp with time zone default (CURRENT_TIMESTAMP + '10 days'::interval) not null,
    winners_count  integer                  default 1                                         not null
);

alter table stage
    owner to postgres;

create table if not exists "user"
(
    id        bigint generated by default as identity
        constraint user_pk
            primary key,
    nick_name varchar(50)  not null,
    email     varchar(255) not null
);

alter table "user"
    owner to postgres;

create table if not exists track
(
    id        bigint       not null
        constraint track_pk
            primary key,
    title     varchar(100) not null,
    mp3_link  text         not null,
    text_link text         not null,
    user_id   bigint       not null
        constraint track_user_fk
            references "user",
    stage_id  bigint       not null
        constraint track_stage_fk
            references stage
);

alter table track
    owner to postgres;

create table if not exists grade
(
    id    bigint not null
        constraint grade_pk
            primary key,
    value boolean,
    judge bigint not null
        constraint grade_judge_fk
            references "user",
    track bigint not null
        constraint grade_track_fk
            references track
);

alter table grade
    owner to postgres;

create table if not exists judge
(
    judge_id bigint not null
        constraint judges_user_fk
            references "user",
    stage_id bigint not null
        constraint judges_stage_fk
            references stage,
    constraint judges_pk
        primary key (stage_id, judge_id)
);

alter table judge
    owner to postgres;

create table if not exists moderator
(
    moderator_id   bigint not null
        constraint moderator_user_fk
            references "user",
    competition_id bigint not null
        constraint moderator_competition_fk
            references competition,
    constraint moderator_pk
        primary key (competition_id, moderator_id)
);

alter table moderator
    owner to postgres;

create table if not exists pair
(
    id          bigint generated by default as identity
        constraint pair_pk
            primary key,
    player_id_1 bigint not null
        constraint pair_user_id_1_fk
            references "user",
    player_id_2 bigint not null
        constraint pair_user_id_2_fk
            references "user",
    stage_id    bigint not null
        constraint pair_stage_fk
            references stage,
    constraint pair_uk
        unique (player_id_1, player_id_2, stage_id)
);

alter table pair
    owner to postgres;

